{{- define "logging-operator.fluentd.root" -}}
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentdConfig
metadata:
  name: {{ .Release.Name }}-root
spec:
  {{- if .Values.loggingServiceAccountAnnotations.root }}
  serviceAccount:
    metadata:
      annotations:
      {{- with .Values.loggingServiceAccountAnnotations.root }}
      {{ toYaml . | indent 8 }}
      {{- end }}
  {{- end -}}
{{- end }}
{{- include "logging-operator.fluentd" (list . "logging-operator.fluentd.root") -}}