{{- define "logging-operator.fluentd.eks" -}}
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentdConfig
metadata:
  name: {{ .Release.Name }}-eks
spec:
  {{- if .Values.loggingServiceAccountAnnotations.eks -}}
  serviceAccount:
    metadata:
      annotations:
      {{- with .Values.loggingServiceAccountAnnotations.eks }}
      {{ toYaml . | indent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.additionalLoggingSources.eks.enabled  }}
{{- include "logging-operator.fluentd" (list . "logging-operator.fluentd.eks") -}}
{{- end }}