{{- define "logging-operator.logging.eks" -}}
metadata:
  name: {{ .Release.Name }}-eks
{{- end -}}
{{- if .Values.additionalLoggingSources.eks.enabled }}
{{- include "logging-operator.logging" (list . "logging-operator.logging.eks") -}}
{{- end }}
